name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch
      - uat   # Trigger workflow on pushes to the uat branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Set the Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python manage.py test  # Run Django tests

      - name: Security Scanning
        # Add your security scanning step here
        # For example, use OWASP ZAP or other security scanning tool

      - name: Deploy to Localhost
        # Add your deployment step here
        # For example, deploy to localhost using Docker or other method
